[package]
name = "dybuk"
description = "Core business logic and encryption engine for Dybuk"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
aes-gcm.workspace = true
argon2.workspace = true
chrono.workspace = true
rand.workspace = true
zeroize.workspace = true
pulldown-cmark.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
