[package]
name = "dybuk-desktop"
description = "Dybuk Desktop Application"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
chrono.workspace = true
dybuk.workspace = true
tauri.workspace = true
tauri-plugin-opener.workspace = true
serde.workspace = true
serde_json.workspace = true
rfd = "0.15"
notify = "6.1"
